title: "&aGenel Ayarlar - %claim_name%"
size: 27

items:
  filler:
    material: BLACK_STAINED_GLASS_PANE
    displayName: "&r"
    slots: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]

  animal_spawning:
    type: animal_spawning
    material: WHEAT
    displayName: "&eHayvan Doğma: &a%animal_spawning%"
    lore:
      - "&7Bu ayarı kapatırsan claim içinde"
      - "&7hayvanlar doğmaz."
      - ""
      - "&eDurum: &a%animal_spawning%"
      - "&7Tıklayarak değiştir."
    slot: 10

  monster_spawning:
    type: monster_spawning
    material: ZOMBIE_HEAD
    displayName: "&eCanavar Doğma: &a%monster_spawning%"
    lore:
      - "&7Bu ayarı kapatırsan claim içinde"
      - "&7canavarlar doğmaz."
      - ""
      - "&eDurum: &a%monster_spawning%"
      - "&7Tıklayarak değiştir."
    slot: 12

  fire_spread:
    type: fire_spread
    material: FLINT_AND_STEEL
    displayName: "&eAteş Yayılması: &a%fire_spread%"
    lore:
      - "&7Bu ayarı kapatırsan claim içinde"
      - "&7ateş yayılmaz."
      - ""
      - "&eDurum: &a%fire_spread%"
      - "&7Tıklayarak değiştir."
    slot: 14

  allow_pvp:
    type: allow_pvp
    material: DIAMOND_SWORD
    displayName: "&ePvP: &a%pvp%"
    lore:
      - "&7Bu ayarı kapatırsan claim içinde"
      - "&7oyuncular birbirine vuramaz."
      - ""
      - "&eDurum: &a%pvp%"
      - "&7Tıklayarak değiştir."
    slot: 16

  back:
    type: back
    material: BARRIER
    displayName: "&cGeri Dön"
    slot: 18
