
### types ###
# general_settings
# player_settings
# back


title: "&eAyarlar Menüsü"
size: 27

items:
  filler:
    material: BLACK_STAINED_GLASS_PANE
    displayName: "&r"
    slots: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]

  general-settings:
    material: BOOK
    displayName: "&aGenel Ayarlar"
    slot: 11
    type: general_settings
  player-settings:
    material: PLAYER_HEAD
    displayName: "&bOyuncu Ayarları"
    slot: 15
    type: player_settings
  back:
    material: ARROW
    displayName: "&cGeri"
    slot: 18
    type: back
