### types ###
# back
# toggle_block_break
# toggle_block_break
# toggle_spawner_break
# toggle_chest_access
# toggle_door_open
# toggle_trap_door_open

title: "Oyuncu Ayarları: %trusted%"
size: 27
items:
  filler:
    material: BLACK_STAINED_GLASS_PANE
    displayName: '&r'
    slots: [0,1,2,3,4,5,6,7,8,9,11,13,15,17,18,19,20,21,22,23,24,25,26]

  back:
    material: ARROW
    displayName: "&c← Geri Dön"
    lore:
      - "&7Önceki menüye dönmek için tıkla."
    slot: 18
    type: "back"

  block_break:
    material: DIAMOND_PICKAXE
    displayName: "&eBlok Kırma: %player_allowBlockBreak%"
    lore:
      - "&7Bu ayar açık olduğunda,"
      - "&f%trusted% &7claim içindeki blokları kırabilir."
      - "&8Durum: %player_allowBlockBreak%"
      - ""
      - "&eTıklayarak değiştir."
    slot: 10
    type: "toggle_block_break"

  block_place:
    material: GRASS_BLOCK
    displayName: "&eBlok Yerleştirme: %player_allowBlockPlace%"
    lore:
      - "&7Bu ayar açık olduğunda,"
      - "&f%trusted% &7claim içine blok yerleştirebilir."
      - "&8Durum: %player_allowBlockPlace%"
      - ""
      - "&eTıklayarak değiştir."
    slot: 12
    type: "toggle_block_place"

  spawner_break:
    material: SPAWNER
    displayName: "&eSpawner Kırma: %player_allowSpawnerBreak%"
    lore:
      - "&7Bu ayar açık olduğunda,"
      - "&f%trusted% &7claim içindeki spawnerları kırabilir."
      - "&8Durum: %player_allowSpawnerBreak%"
      - ""
      - "&eTıklayarak değiştir."
    slot: 14
    type: "toggle_spawner_break"

  chest_access:
    material: CHEST
    displayName: "&eSandık Erişimi: %player_allowChestAccess%"
    lore:
      - "&7Bu ayar açık olduğunda,"
      - "&f%trusted% &7claim içindeki sandıkları açabilir."
      - "&8Durum: %player_allowChestAccess%"
      - ""
      - "&eTıklayarak değiştir."
    slot: 16
    type: "toggle_chest_access"
  allow_door_open:
    material: IRON_DOOR
    displayName: "&eKapı Erişimi: %player_allowDoorOpen%"
    lore:
      - "&7Bu ayar açık olduğunda,"
      - "&f%trusted% &7claim içindeki kapıları açabilir."
      - "&8Durum: %player_allowDoorOpen%"
      - ""
      - "&eTıklayarak değiştir."
    slot: 20
    type: toggle_door_open
  allow_trap_door_open:
    material: IRON_TRAPDOOR
    displayName: "&eTuzak Kapısı Erişimi: %player_allowTrapDoorOpen%"
    lore:
      - "&7Bu ayar açık olduğunda,"
      - "&f%trusted% &7claim içindeki tuzak kapılarını açabilir."
      - "&8Durum: %player_allowTrapDoorOpen%"
      - ""
      - "&eTıklayarak değiştir."
    slot: 24
    type: "toggle_trap_door_open"
